import type { ThemeItemStyleMap, ThemePreference } from './themeTypes'

/** Distinct button + outfit-log colors for every stable closet item in each manual theme. */
export const DEFAULT_THEME_ITEM_STYLES: Record<ThemePreference, ThemeItemStyleMap> = {
  royal: {
    'gold-tiara': {
      background: '#fef9c3',
      text: '#854d0e',
      border: '#facc15',
      heartColor: '#eab308',
      motifShape: 'star',
    },
    'diamond-crown': {
      background: '#e0f2fe',
      text: '#0369a1',
      border: '#38bdf8',
      heartColor: '#0ea5e9',
      motifShape: 'star',
    },
    'pink-gown': {
      background: '#fce7f3',
      text: '#be185d',
      border: '#f472b6',
      heartColor: '#ec4899',
      motifShape: 'heart',
    },
    'purple-dress': {
      background: '#f3e8ff',
      text: '#6b21a8',
      border: '#a855f7',
      heartColor: '#9333ea',
      motifShape: 'heart',
    },
    'emerald-gown': {
      background: '#d1fae5',
      text: '#065f46',
      border: '#34d399',
      heartColor: '#10b981',
      motifShape: 'heart',
    },
    'glass-slippers': {
      background: '#f0f9ff',
      text: '#0c4a6e',
      border: '#7dd3fc',
      heartColor: '#38bdf8',
      motifShape: 'circle',
    },
    'riding-boots': {
      background: '#fef3c7',
      text: '#78350f',
      border: '#d97706',
      heartColor: '#b45309',
      motifShape: 'circle',
    },
  },
  space: {
    'gold-tiara': {
      background: '#e5e7eb',
      text: '#1f2937',
      border: '#94a3b8',
      heartColor: '#64748b',
      motifShape: 'star',
    },
    'diamond-crown': {
      background: '#e0f2fe',
      text: '#075985',
      border: '#38bdf8',
      heartColor: '#0284c7',
      motifShape: 'star',
    },
    'pink-gown': {
      background: '#eff6ff',
      text: '#1d4ed8',
      border: '#93c5fd',
      heartColor: '#2563eb',
      motifShape: 'square',
    },
    'purple-dress': {
      background: '#ede9fe',
      text: '#5b21b6',
      border: '#8b5cf6',
      heartColor: '#7c3aed',
      motifShape: 'square',
    },
    'emerald-gown': {
      background: '#ccfbf1',
      text: '#0f766e',
      border: '#2dd4bf',
      heartColor: '#14b8a6',
      motifShape: 'square',
    },
    'glass-slippers': {
      background: '#f8fafc',
      text: '#334155',
      border: '#cbd5e1',
      heartColor: '#94a3b8',
      motifShape: 'circle',
    },
    'riding-boots': {
      background: '#dbeafe',
      text: '#1e40af',
      border: '#2563eb',
      heartColor: '#1d4ed8',
      motifShape: 'circle',
    },
  },
  dinosaurs: {
    'gold-tiara': {
      background: '#fef3c7',
      text: '#78350f',
      border: '#d97706',
      heartColor: '#ea580c',
      motifShape: 'triangle',
    },
    'diamond-crown': {
      background: '#ecfccb',
      text: '#365314',
      border: '#84cc16',
      heartColor: '#65a30d',
      motifShape: 'triangle',
    },
    'pink-gown': {
      background: '#ffedd5',
      text: '#9a3412',
      border: '#fb923c',
      heartColor: '#f97316',
      motifShape: 'square',
    },
    'purple-dress': {
      background: '#fef9c3',
      text: '#854d0e',
      border: '#eab308',
      heartColor: '#ca8a04',
      motifShape: 'square',
    },
    'emerald-gown': {
      background: '#dcfce7',
      text: '#166534',
      border: '#22c55e',
      heartColor: '#16a34a',
      motifShape: 'square',
    },
    'glass-slippers': {
      background: '#fef3c7',
      text: '#92400e',
      border: '#f59e0b',
      heartColor: '#d97706',
      motifShape: 'circle',
    },
    'riding-boots': {
      background: '#fed7aa',
      text: '#7c2d12',
      border: '#c2410c',
      heartColor: '#9a3412',
      motifShape: 'circle',
    },
  },
  animals: {
    'gold-tiara': {
      background: '#fef3c7',
      text: '#78350f',
      border: '#d97706',
      heartColor: '#f59e0b',
      motifShape: 'circle',
    },
    'diamond-crown': {
      background: '#dcfce7',
      text: '#166534',
      border: '#22c55e',
      heartColor: '#16a34a',
      motifShape: 'circle',
    },
    'pink-gown': {
      background: '#ffedd5',
      text: '#9a3412',
      border: '#f97316',
      heartColor: '#ea580c',
      motifShape: 'paw',
    },
    'purple-dress': {
      background: '#f8fafc',
      text: '#111827',
      border: '#64748b',
      heartColor: '#334155',
      motifShape: 'paw',
    },
    'emerald-gown': {
      background: '#fee2e2',
      text: '#991b1b',
      border: '#ef4444',
      heartColor: '#dc2626',
      motifShape: 'paw',
    },
    'glass-slippers': {
      background: '#ecfdf5',
      text: '#047857',
      border: '#34d399',
      heartColor: '#10b981',
      motifShape: 'circle',
    },
    'riding-boots': {
      background: '#dbeafe',
      text: '#1e40af',
      border: '#3b82f6',
      heartColor: '#2563eb',
      motifShape: 'circle',
    },
  },
  sports: {
    'gold-tiara': {
      background: '#dbeafe',
      text: '#1e40af',
      border: '#3b82f6',
      heartColor: '#2563eb',
      motifShape: 'circle',
    },
    'diamond-crown': {
      background: '#fef3c7',
      text: '#92400e',
      border: '#f59e0b',
      heartColor: '#d97706',
      motifShape: 'circle',
    },
    'pink-gown': {
      background: '#fee2e2',
      text: '#991b1b',
      border: '#ef4444',
      heartColor: '#dc2626',
      motifShape: 'square',
    },
    'purple-dress': {
      background: '#e0f2fe',
      text: '#075985',
      border: '#38bdf8',
      heartColor: '#0284c7',
      motifShape: 'square',
    },
    'emerald-gown': {
      background: '#dcfce7',
      text: '#166534',
      border: '#22c55e',
      heartColor: '#16a34a',
      motifShape: 'square',
    },
    'glass-slippers': {
      background: '#fff7ed',
      text: '#9a3412',
      border: '#fb923c',
      heartColor: '#f97316',
      motifShape: 'circle',
    },
    'riding-boots': {
      background: '#f3e8ff',
      text: '#6b21a8',
      border: '#a855f7',
      heartColor: '#9333ea',
      motifShape: 'circle',
    },
  },
  surprise: {
    'gold-tiara': {
      background: '#fef9c3',
      text: '#854d0e',
      border: '#facc15',
      heartColor: '#eab308',
      motifShape: 'diamond',
    },
    'diamond-crown': {
      background: '#fce7f3',
      text: '#be185d',
      border: '#f472b6',
      heartColor: '#ec4899',
      motifShape: 'diamond',
    },
    'pink-gown': {
      background: '#ede9fe',
      text: '#5b21b6',
      border: '#8b5cf6',
      heartColor: '#7c3aed',
      motifShape: 'heart',
    },
    'purple-dress': {
      background: '#cffafe',
      text: '#155e75',
      border: '#22d3ee',
      heartColor: '#06b6d4',
      motifShape: 'heart',
    },
    'emerald-gown': {
      background: '#fef3c7',
      text: '#92400e',
      border: '#fbbf24',
      heartColor: '#f59e0b',
      motifShape: 'heart',
    },
    'glass-slippers': {
      background: '#dcfce7',
      text: '#166534',
      border: '#4ade80',
      heartColor: '#22c55e',
      motifShape: 'circle',
    },
    'riding-boots': {
      background: '#ffe4e6',
      text: '#9f1239',
      border: '#fb7185',
      heartColor: '#f43f5e',
      motifShape: 'circle',
    },
  },
}
