export function iconForThemeLabel(label: string | undefined, fallback: string) {
  const normalized = label?.toLowerCase() ?? ''
  if (normalized.includes('star helmet')) return '⭐'
  if (normalized.includes('silver helmet')) return '🪖'
  if (normalized.includes('blue suit') || normalized.includes('blue cap')) return '🔵'
  if (normalized.includes('purple suit') || normalized.includes('purple pennant')) return '🟣'
  if (normalized.includes('comet')) return '☄️'
  if (normalized.includes('moon')) return '🌙'
  if (normalized.includes('jet') || normalized.includes('rocket')) return '🚀'
  if (normalized.includes('leaf')) return '🍃'
  if (normalized.includes('amber')) return '🟠'
  if (normalized.includes('camo')) return '🟩'
  if (normalized.includes('mud')) return '🟤'
  if (normalized.includes('climber')) return '🧗'
  if (normalized.includes('trail')) return '🥾'
  if (normalized.includes('creek')) return '💧'
  if (normalized.includes('striker')) return '⚽'
  if (normalized.includes('goalie')) return '🥅'
  if (normalized.includes('captain')) return '©️'
  if (normalized.includes('sprint')) return '🏃'
  if (normalized.includes('court')) return '🎾'
  if (normalized.includes('spark')) return '✨'
  if (normalized.includes('glow')) return '💡'
  if (normalized.includes('rainbow')) return '🌈'
  if (normalized.includes('cloud')) return '☁️'
  if (normalized.includes('bounce')) return '🟠'
  if (normalized.includes('glide')) return '🛼'
  if (normalized.includes('panda')) return '🐼'
  if (normalized.includes('tiger')) return '🐯'
  if (normalized.includes('fox')) return '🦊'
  if (normalized.includes('lion')) return '🦁'
  if (normalized.includes('helmet')) return '🪖'
  if (normalized.includes('satellite')) return '🛰️'
  if (normalized.includes('fossil') || normalized.includes('bone')) return '🦴'
  if (normalized.includes('volcano')) return '🌋'
  if (normalized.includes('egg')) return '🥚'
  if (normalized.includes('soccer')) return '⚽'
  if (normalized.includes('football')) return '🏈'
  if (normalized.includes('basketball')) return '🏀'
  if (normalized.includes('trophy')) return '🏆'
  if (normalized.includes('medal')) return '🏅'
  if (normalized.includes('safari')) return '🧭'
  if (normalized.includes('rescue')) return '⛑️'
  if (normalized.includes('ranger')) return '🧢'
  if (normalized.includes('gold cap')) return '🟡'
  if (normalized.includes('cap') || normalized.includes('hat')) return '🧢'
  if (normalized.includes('shoe') || normalized.includes('sneaker')) return '👟'
  if (normalized.includes('boot')) return '🥾'
  return fallback
}
